//CASE CALLS
export const FETCH_HOT_CASES = 'FETCH_HOT_CASES';
export const FETCH_NEW_CASES = 'FETCH_NEW_CASES';
export const FETCH_CASE_BY_ID = 'FETCH_CASE_BY_ID';

//AUTHENTICATION CALLS
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";

//ACCOUNT CALLS
export const FETCH_USER = "FETCH_USER";