//CASE CALLS
export const FETCH_HOT_CASES = 'FETCH_HOT_CASES';
export const FETCH_CASE_BY_ID = 'FETCH_CASE_BY_ID';
export const OPEN_CASE_BY_ID = 'OPEN_CASE_BY_ID';

//AUTHENTICATION CALLS
export const LOGIN = "LOGIN";

//ACCOUNT CALLS
export const FETCH_USER = "FETCH_USER";
export const REGISTER = "REGISTER";

//BANK ACCOUNT CALLS
export const CREATE_BANKACCOUNT = "CREATE_BANKACCOUNT";
export const LINK_TO_BANKACCOUNT = "LINK_TO_BANKACCOUNT";

//INVENTORY CALLS
export const GET_INVENTORY = "GET_INVENTORY";
export const FETCH_ITEM_BY_ID = "FETCH_ITEM_BY_ID";

//GAMBLING ACCOUNT CALLS
export const GET_ACCOUNT = "GET_ACCOUNT";
export const BUY_TOKENS = "BUY_TOKENS";

//GAMBLING GAME CALLS
export const OPEN_CASE = "OPEN_CASE";
export const PLAY_HILOW = "PLAY_HILOW";
export const PLAY_ROULETTE = "PLAY_ROULETTE";
